from pathlib import Path
import json
import subprocess
import sys
import tempfile
import shutil

# root path relative to current file
ROOT = Path(__file__).resolve().parent.parent

# Suricata detections file
SURICATA_RULES_DIR = ROOT / "detections" / "security-onion" / "suricata"

# Suricata tests directory
TESTS_DIR = ROOT / "tests" / "suricata"


# fail function
def fail(msg: str):
    print(f"[FAIL] {msg}")
    sys.exit(1)


# log function
def log(msg: str):
    print(f"[INFO] {msg}")


# runs command to ensure Suricata is installed
def check_suricata_installed():
    try:
        subprocess.run(["suricata", "-V"], capture_output=True, check=True)
    except Exception:
        fail("Suricata is not installed or not in PATH on runner")


# load the test configuration
def load_test_config(rule_stem: str) -> dict:
    # test path
    config_path = TESTS_DIR / rule_stem / "test_config.json"

    if not config_path.exists():
        fail(f"Missing test_config.json for {rule_stem}")

    return json.loads(config_path.read_text())


# takes a Suricata rule and replays one or more PCAP files against it in
# isolate environment. parses eve.json as output and counts alerts matching the
# expected SID
def run_suricata_test(rule_file: Path, test_dir: Path):
    rule_stem = rule_file.stem
    config = load_test_config(rule_stem)

    # expected values
    expected_sid = int(config["expected_sid"])
    expected_min = int(config.get("expected_alert_min", 1))

    # pull positive PCAP files
    pcap_dir = test_dir / "positive"
    pcaps = list(pcap_dir.glob("*.pcap"))

    if not pcaps:
        fail(f"No pcap files found for {rule_stem}")

    # temp working dir
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        rules_file = tmp_path / "test.rules"
        rules_file.write_text(rule_file.read_text())

        eve_file = tmp_path / "eve.json"

        # run Suricata rule against PCAPs
        for pcap in pcaps:
            log(f"Running Suricata on {pcap.name} for {rule_stem}")

            cmd = [
                "suricata",            # initiates Suricata if on system PATH
                "-r", str(pcap),       # read packets from PCAP
                "-S", str(rules_file), # use only the temporary test rule file
                "-l", str(tmp_path),   # write logs/outputs into the temp directory
                "--init-errors-fatal", # fail on init issues
            ]

            result = subprocess.run(cmd, capture_output=True, text=True)

            if result.returncode != 0:
                fail(f"Suricata failed:\n{result.stderr}")

        if not eve_file.exists():
            fail("Suricata did not produce eve.json")

        alerts = 0

        # parse eve.json line-by-line
        with eve_file.open() as f:
            for line in f:
                try:
                    event = json.loads(line)
                except:
                    continue

                # only alert events are relevant for rule validation
                if event.get("event_type") != "alert":
                    continue

                # count only alerts generated by the expected SID for this rule
                alert = event.get("alert", {})
                if alert.get("signature_id") == expected_sid:
                    alerts += 1

        log(f"{rule_stem} produced {alerts} alerts (expected >= {expected_min})")

        if alerts < expected_min:
            fail(f"{rule_stem} failed: expected >= {expected_min}, got {alerts}")

        log(f"{rule_stem} passed")


def main():
    check_suricata_installed()

    if not SURICATA_RULES_DIR.exists():
        fail("Suricata rules directory missing")

    # iterate through each Suricata rule file in the repo
    for rule_file in SURICATA_RULES_DIR.glob("*.rules"):
        test_dir = TESTS_DIR / rule_file.stem

        # verify rules have a matching test directory
        if not test_dir.exists():
            fail(
                f"Missing test directory for {rule_file.name}: "
                f"{test_dir.relative_to(ROOT)}"
            )

        # each test directory must contain a test_config.json file
        if not test_dir.is_dir():
            fail(
                f"Test path for {rule_file.name} is not a directory: "
                f"{test_dir.relative_to(ROOT)}"
            )

        # each test directory must contain a test_config.json file
        config_path = test_dir / "test_config.json"
        if not config_path.exists():
            fail(
                f"Missing test_config.json for {rule_file.name}: "
                f"{config_path.relative_to(ROOT)}"
            )

        # execute isolated Suricata rule test for current detection
        run_suricata_test(rule_file, test_dir)

    print("[PASS] Suricata detection tests passed")


if __name__ == "__main__":
    main()